### ISSUE TITLE
No results found

### ISSUE THREAD

**Issue by XamHans** [sdl/Multiselect-ComboBox#44] opened 2020-07-09 08:47 UTC
Hi There,

i am trying to implement this awesome Multiselect ComboBox. I followed the examples and have following setup
Inside my ViewModel I used the LanguageItem Class with all the Interfaces

` 

            var group = new LanguageItemGroup(0, "All Items");
            Items = new ObservableCollection<LanguageItem>
             {
            new LanguageItem
            {
                Id = "en-US",
                Name= "English (United States)",
                Group = group
            },
            new LanguageItem
            {
                Id = "it-IT",
                Name= "Italian (Italy)",
                Group = group
            },
            new LanguageItem
            {
                Id = "de-DE",
                Name= "German (Germany)",
                Group = group
            }
        };`

My Items ObservableCollection looks like this
`      public ObservableCollection<LanguageItem> Items
        {
            get => _items ?? (_items = new ObservableCollection<LanguageItem>());
            set
            {
                _items = value;
                OnPropertyChanged("Items");
            }
        }
`

Inside XAML i used this Code
`  <sdl:MultiSelectComboBox DataContext="{Binding }" 
                                                        ItemsSource="{Binding Items}"
                                                        IsEditable="true"
                                                        SelectionMode="Multiple"/>`

The Items Collection is correctly called and returns the 3 Items i initialized in the viewmodel, but the MultiSelectComboBox only shows "No results found"

![NoResults](https://user-images.githubusercontent.com/40567147/87018388-7399b400-c1d1-11ea-9210-a9eac5e1176f.PNG)

**Comment by kt1996** [comment] 2020-07-09 10:35
I am encountering the same issue. Able to see the items in code using breakpoints but the combobox shows "No results found"

**Comment by XamHans** [comment] 2020-07-10 06:15
@kt1996  Thank you, with version 1.0.16 its working fine.
When i downgraded I noticed, that the window could not be correctly initalized ( freezing ui), but after a restart its working fine

**Comment by cromica** [comment] 2020-07-10 10:15
@Impertatore  Seems that we have a small regression in the latest build.

**Comment by kt1996** [comment] 2020-07-20 05:43
Have mailed basic stripped down project even with which i am facing the issue to phartnett@sdl.com. Please advise if  I can assist with anything else to debug the issue :)

**Comment by Impertatore** [comment] 2020-07-21 07:29
Hi @kt1996, Sorry to hear you are having issues implementing this control and thank you for providing the source code example.  The only thing I see that is incorrect with your implementation is that the data is not binding correctly to the item collection.

Try to separate concerns and provide assign the data context, let the controls in the view bind to the collection in the view model; the view model should not need to know anything about the design structure.  I have updated your example code with the minimum changes to demonstrate this.  Once you make these changes, then it will work as expected.

let me know how it goes,
P.

[Example.updated.zip](https://github.com/sdl/Multiselect-ComboBox/files/4951834/Example.updated.zip)

Hi @XamHans, can you please provide me with an example of your source code?

**Comment by kt1996** [comment] 2020-07-23 15:56
Hey @Impertatore,
Apologies for the delayed reply; got a bit busy and wasn't able to check impromptu. The example provided by you works perfectly. However, I noticed I was still facing the "No results found" issue when using in the project I was originally developing and was able to debug to the point that when the control is added to say a tab which is not visible at start this occurs.
Have mailed the example codes; the control on the first tab which is loaded into view from start works perfectly, however if the control is not in view on load (like for second tab), no results found is returned.  Thanks again, awaiting your response :)

**Comment by Impertatore** [comment] 2020-07-24 09:17
Hi @kt1996 

The problem you are now experiencing is related to a common problem when working with the .net TabControl, where the context is assigned to the selected tab…
There a few workarounds to dealing with this... like binding to Freezable object in the tab etc…

You can also simply wait for window (or view) to be fully loaded and then bind the collection to the controls in the view.  You can accomplish this by inject the window/view to the view Model and then subscribing to the Loaded event. 

I have provided here a more complete example to demonstrate this.
[MultiSelectControlCodes.zip](https://github.com/sdl/Multiselect-ComboBox/files/4971117/MultiSelectControlCodes.zip)

**Comment by Impertatore** [comment] 2020-07-24 12:07
Hi both @kt1996 & @XamHans, 
The issues reported seem to be related how you implement the control. I will close this issue in the next days if there are no actual problems to report against the latest release 1.0.18

@XamHans, please send to me (phartnett@sdl.com) a more complete version of the source code to demonstrate the problem you have reported if different to what was diagnosed/discussed for @kt1996.

Thank you for your continuing support with this project.
P.

**Comment by kt1996** [comment] 2020-07-27 10:23
Hey @Impertatore,
Thanks for pinpointing that its an issue with .net TabControl context. Wasnt aware of it earlier and was under the impression that it is an issue with the MultiSelect control since with v1.0.17 and before explicitly binding the itemsource (even though data-context was providing binding information) to control did the trick; and it this broke with v1.0.18 onwards.

Also need an advice on workarounds for Multi-Tab scenarios (and not just two tabs). For the example project you have attached where view is injected with binding done after load, successful binding happens for only two cases; the tab which has the isSelected property to true when the view is injected, and the tab which gets selected when the binding gets completed (int SelectedTab)'s value in the viewmodel. A control in any other third tab with binding for it done even with the injected view's load handle subscription fails to bind.

Much grateful for all the help :D

**Comment by Impertatore** [comment] 2020-07-27 16:05
Hi @kt1996,  The updates included with version 1.0.18 remove a treading issued caused by the control calling itself; a side-effect of this is what you described as working with earlier releases ;-)  

Personally, outside of creating quick demo code, I have rarely used the vanilla TabControl provided with the .Net framework without creating a custom control of it -> in some fashion or other...  
You can find numerous examples of how to work with the TabControl; google search!

**Comment by kt1996** [comment] 2020-08-05 07:35
Hello @Impertatore,
I have mailed you another set of minimal project codes to demonstrate the issue where the data binding to control is not happening even in a window which has no tabControl which you diagnosed. (Project consists of mainWindow opening another window where the control is rendered, mainWindow just has a button control and secondary window just has the multiselect control.)

This issue appears to be happening, whenever the control is in a view that is not rendered at start. Please correct me if I am wrong somewhere. Thanks :)

**Comment by Impertatore** [comment] 2020-08-05 10:51
Hi @kt1996,
It seems like you are trying to bind to an object on the window before the data tree is available.  You will need to wait until the window has loaded before assigning the data context.  
Make reference to a similar issue with response from here: [Issue 5](https://github.com/sdl/Multiselect-ComboBox/issues/5)


Note: Please try to create a new issue for new problems/issues that you would like to report, to avoid scope-creep

**Comment by kt1996** [comment] 2020-08-05 15:23
Hello @Impertatore, 
Thanks a lot for the prompt reply. As suggested assigning data context after data tree is available by subscribing to the window's event handler worked perfectly and it appears to be a different issue due to incorrect implementation on my end. Please close this issue back again, thank you!

**Closed** 2020-08-05 16:53 UTC
